const imageVersion = "illustration-v2";

export const bookCategories = [
  {
    id: "animals",
    label: "动物",
    sceneSlug: "scene-animals",
    sceneQuery: "meadow animals rabbit duck kitten butterfly",
    title: "动物",
    subtitle: "在草地上，和小动物打招呼。",
    theme: "green",
    question: "它有什么特别的外形？会发出什么声音？",
    items: [
      ["rabbit", "rabbit animal", "小兔", "xiao tu", "白色，长耳朵", "白色", "长耳朵"],
      ["duckling", "duckling animal", "小鸭", "xiao ya", "黄色，会游水", "黄色", "扁嘴巴"],
      ["kitten", "kitten animal", "小猫", "xiao mao", "柔软，会喵喵叫", "灰白", "小爪子"],
      ["butterfly", "butterfly insect", "蝴蝶", "hu die", "彩色，会飞", "彩色", "大翅膀"],
      ["puppy", "puppy dog animal", "小狗", "xiao gou", "活泼，会汪汪叫", "棕色", "小耳朵"],
      ["lamb", "lamb animal", "小羊", "xiao yang", "白色，毛卷卷", "白色", "卷毛"],
      ["calf", "calf cow animal", "小牛", "xiao niu", "强壮，爱吃草", "黑白", "大眼睛"],
      ["foal", "foal horse animal", "小马", "xiao ma", "会奔跑，腿长长", "棕色", "长腿"],
      ["chick", "chick animal", "小鸡", "xiao ji", "黄色，叽叽叫", "黄色", "小尖嘴"],
      ["goldfish", "goldfish fish", "金鱼", "jin yu", "橙色，会游泳", "橙色", "鱼鳍"],
      ["turtle", "turtle animal", "乌龟", "wu gui", "背着硬硬的壳", "绿色", "圆壳"],
      ["frog", "frog animal", "青蛙", "qing wa", "绿色，会跳", "绿色", "长后腿"],
      ["penguin", "penguin animal", "企鹅", "qi e", "黑白色，摇摇走", "黑白", "短翅膀"],
      ["elephant", "elephant animal", "大象", "da xiang", "灰色，鼻子长", "灰色", "长鼻子"],
      ["giraffe", "giraffe animal", "长颈鹿", "chang jing lu", "脖子很长", "黄色", "长脖子"],
      ["panda", "panda animal", "熊猫", "xiong mao", "黑白色，爱吃竹子", "黑白", "圆耳朵"],
      ["lion", "lion animal", "狮子", "shi zi", "金黄色，鬃毛多", "金黄", "鬃毛"],
      ["zebra", "zebra animal", "斑马", "ban ma", "黑白条纹", "黑白", "条纹"],
      ["koala", "koala animal", "考拉", "kao la", "灰色，抱树枝", "灰色", "圆耳朵"],
      ["dolphin", "dolphin animal", "海豚", "hai tun", "蓝灰色，会跃出水面", "蓝灰", "流线形"],
    ],
  },
  {
    id: "plants",
    label: "植物",
    sceneSlug: "scene-plants",
    sceneQuery: "botanical garden flowers leaves seedlings",
    title: "植物",
    subtitle: "观察叶子、花朵和小小的芽。",
    theme: "leaf",
    question: "它的叶子是什么颜色？花朵是什么形状？",
    items: [
      ["sunflower", "sunflower flower", "向日葵", "xiang ri kui", "黄色，朝太阳", "黄色", "大花盘"],
      ["lotus", "lotus leaf flower", "荷叶", "he ye", "绿色，圆圆的", "绿色", "圆形"],
      ["seedling", "seedling plant", "小树苗", "xiao shu miao", "嫩绿，慢慢长高", "嫩绿", "小叶子"],
      ["fern", "fern plant", "蕨类", "jue lei", "绿色，像羽毛", "绿色", "卷叶"],
      ["rose", "rose flower", "玫瑰", "mei gui", "红色，有花瓣", "红色", "层层花瓣"],
      ["tulip", "tulip flower", "郁金香", "yu jin xiang", "杯子形的花", "粉色", "杯形"],
      ["daisy", "daisy flower", "雏菊", "chu ju", "白色花瓣，黄色花心", "白色", "小圆花"],
      ["bamboo", "bamboo plant", "竹子", "zhu zi", "绿色，一节一节", "绿色", "长杆"],
      ["pine", "pine tree", "松树", "song shu", "针一样的叶子", "深绿", "针叶"],
      ["maple", "maple leaf", "枫叶", "feng ye", "秋天会变红", "红色", "掌形叶"],
      ["cactus", "cactus plant", "仙人掌", "xian ren zhang", "绿色，有小刺", "绿色", "厚厚的茎"],
      ["grass", "green grass plant", "小草", "xiao cao", "细细长长", "绿色", "细长叶"],
      ["lavender", "lavender flower", "薰衣草", "xun yi cao", "紫色，有香味", "紫色", "小花穗"],
      ["orchid", "orchid flower", "兰花", "lan hua", "花瓣优雅", "紫白", "弯花瓣"],
      ["mushroom", "mushroom", "蘑菇", "mo gu", "像一把小伞", "棕色", "伞形"],
      ["water-lily", "water lily flower", "睡莲", "shui lian", "开在水面上", "粉色", "圆花瓣"],
      ["ivy", "ivy leaves plant", "常春藤", "chang chun teng", "会攀爬", "绿色", "藤蔓"],
      ["mint", "mint plant leaves", "薄荷", "bo he", "叶子清香", "绿色", "椭圆叶"],
      ["clover", "clover plant", "三叶草", "san ye cao", "三片小叶子", "绿色", "三片叶"],
      ["peony", "peony flower", "牡丹", "mu dan", "花朵大而饱满", "粉色", "大花朵"],
    ],
  },
  {
    id: "vegetables",
    label: "蔬菜",
    sceneSlug: "scene-vegetables",
    sceneQuery: "vegetable garden tomatoes carrots broccoli corn",
    title: "蔬菜",
    subtitle: "来自大地的礼物，营养又美味。",
    theme: "vegetable",
    question: "它是什么颜色？长得像什么形状？",
    items: [
      ["tomato", "tomato vegetable", "西红柿", "xi hong shi", "红色，酸甜可口", "红色", "圆形"],
      ["carrot", "carrot vegetable", "胡萝卜", "hu luo bo", "橙色，长条形", "橙色", "长条形"],
      ["broccoli", "broccoli vegetable", "西兰花", "xi lan hua", "绿色，像小树", "绿色", "树状"],
      ["corn", "corn vegetable", "玉米", "yu mi", "黄色，一粒一粒", "黄色", "长条形"],
      ["eggplant", "eggplant vegetable", "茄子", "qie zi", "紫色，弯弯的", "紫色", "长圆形"],
      ["pumpkin", "pumpkin vegetable", "南瓜", "nan gua", "橙色，圆圆的", "橙色", "圆形"],
      ["cucumber", "cucumber vegetable", "黄瓜", "huang gua", "绿色，脆脆的", "绿色", "长条形"],
      ["potato", "potato vegetable", "土豆", "tu dou", "棕黄色，圆滚滚", "棕黄", "椭圆形"],
      ["pepper", "bell pepper vegetable", "彩椒", "cai jiao", "颜色鲜艳，像小灯笼", "红黄", "灯笼形"],
      ["spinach", "spinach vegetable", "菠菜", "bo cai", "绿色，叶子软", "绿色", "叶片"],
      ["lettuce", "lettuce vegetable", "生菜", "sheng cai", "叶子一层层", "浅绿", "叶片"],
      ["cabbage", "cabbage vegetable", "卷心菜", "juan xin cai", "叶子卷成球", "浅绿", "圆球"],
      ["mushroom", "mushroom vegetable", "香菇", "xiang gu", "棕色，像小伞", "棕色", "伞形"],
      ["onion", "onion vegetable", "洋葱", "yang cong", "一层一层", "紫白", "圆形"],
      ["garlic", "garlic vegetable", "大蒜", "da suan", "白色，一瓣瓣", "白色", "瓣形"],
      ["pea", "green peas vegetable", "豌豆", "wan dou", "绿色，小圆粒", "绿色", "小圆粒"],
      ["radish", "radish vegetable", "白萝卜", "bai luo bo", "白色，长长的", "白色", "长条形"],
      ["celery", "celery vegetable", "芹菜", "qin cai", "绿色，有长茎", "绿色", "长茎"],
      ["cauliflower", "cauliflower vegetable", "花菜", "hua cai", "白色，像小花", "白色", "花状"],
      ["sweet-potato", "sweet potato vegetable", "红薯", "hong shu", "红皮，甜甜的", "红棕", "长圆形"],
    ],
  },
  {
    id: "fruits",
    label: "水果",
    sceneSlug: "scene-fruits",
    sceneQuery: "fruit basket orchard apple banana strawberry orange grapes",
    title: "水果",
    subtitle: "闻一闻果香，认识颜色和味道。",
    theme: "fruit",
    question: "它是什么颜色？尝起来可能是什么味道？",
    items: [
      ["apple", "red apple fruit", "苹果", "ping guo", "红色，圆圆的", "红色", "圆形"],
      ["banana", "banana fruit", "香蕉", "xiang jiao", "黄色，弯弯的", "黄色", "弯形"],
      ["strawberry", "strawberry fruit", "草莓", "cao mei", "红色，有小点", "红色", "心形"],
      ["orange", "orange fruit", "橙子", "cheng zi", "橙色，多汁", "橙色", "圆形"],
      ["grape", "purple grapes fruit", "葡萄", "pu tao", "紫色，一串串", "紫色", "小圆粒"],
      ["pear", "pear fruit", "梨", "li", "黄绿色，甜甜的", "黄绿", "葫芦形"],
      ["peach", "peach fruit", "桃子", "tao zi", "粉色，有绒毛", "粉色", "圆形"],
      ["watermelon", "watermelon fruit", "西瓜", "xi gua", "绿色外皮，红色果肉", "绿红", "大圆形"],
      ["pineapple", "pineapple fruit", "菠萝", "bo luo", "黄色，有格纹", "黄色", "椭圆形"],
      ["mango", "mango fruit", "芒果", "mang guo", "黄色，香香的", "黄色", "椭圆形"],
      ["kiwi", "kiwi fruit", "猕猴桃", "mi hou tao", "棕色外皮，绿色果肉", "棕绿", "椭圆形"],
      ["lemon", "lemon fruit", "柠檬", "ning meng", "黄色，酸酸的", "黄色", "椭圆形"],
      ["blueberry", "blueberry fruit", "蓝莓", "lan mei", "蓝紫色，小小的", "蓝紫", "小圆粒"],
      ["cherry", "cherry fruit", "樱桃", "ying tao", "红色，小圆果", "红色", "小圆形"],
      ["plum", "plum fruit", "李子", "li zi", "紫红色，圆圆的", "紫红", "圆形"],
      ["pomegranate", "pomegranate fruit", "石榴", "shi liu", "红色，籽很多", "红色", "圆形"],
      ["dragon-fruit", "dragon fruit", "火龙果", "huo long guo", "红皮，黑籽", "红白", "椭圆形"],
      ["coconut", "coconut fruit", "椰子", "ye zi", "棕色，壳硬硬", "棕色", "圆形"],
      ["lychee", "lychee fruit", "荔枝", "li zhi", "红色外壳，白色果肉", "红白", "小圆形"],
      ["papaya", "papaya fruit", "木瓜", "mu gua", "橙色果肉，长圆形", "橙色", "长圆形"],
    ],
  },
].map((category) => ({
  ...category,
  image: `/media/optimized/${category.sceneSlug}.webp?v=${imageVersion}`,
  items: category.items.map(([slug, query, name, pinyin, cue, color, shape]) => ({
    slug: `${category.id}-${slug}`,
    query,
    name,
    pinyin,
    cue,
    color,
    shape,
    image: `/media/optimized/${category.id}-${slug}.webp?v=${imageVersion}`,
    focusPosition: "center",
    focusScale: 1,
  })),
}));
