const imageVersion = "illustration-v4";

export const bookCategories = [
  {
    id: "animals",
    label: "动物",
    sceneSlug: "scene-animals",
    sceneQuery: "meadow animals rabbit duck kitten butterfly",
    title: "动物",
    subtitle: "在草地上，和小动物打招呼。",
    theme: "green",
    question: "它有什么特别的外形？会发出什么声音？",
    items: [
      ["rabbit", "rabbit animal", "小兔", "xiao tu", "白色，长耳朵", "白色", "长耳朵"],
      ["duckling", "duckling animal", "小鸭", "xiao ya", "黄色，会游水", "黄色", "扁嘴巴"],
      ["kitten", "kitten animal", "小猫", "xiao mao", "柔软，会喵喵叫", "灰白", "小爪子"],
      ["butterfly", "butterfly insect", "蝴蝶", "hu die", "彩色，会飞", "彩色", "大翅膀"],
      ["puppy", "puppy dog animal", "小狗", "xiao gou", "活泼，会汪汪叫", "棕色", "小耳朵"],
      ["lamb", "lamb animal", "小羊", "xiao yang", "白色，毛卷卷", "白色", "卷毛"],
      ["calf", "calf cow animal", "小牛", "xiao niu", "强壮，爱吃草", "黑白", "大眼睛"],
      ["foal", "foal horse animal", "小马", "xiao ma", "会奔跑，腿长长", "棕色", "长腿"],
      ["chick", "chick animal", "小鸡", "xiao ji", "黄色，叽叽叫", "黄色", "小尖嘴"],
      ["goldfish", "goldfish fish", "金鱼", "jin yu", "橙色，会游泳", "橙色", "鱼鳍"],
      ["turtle", "turtle animal", "乌龟", "wu gui", "背着硬硬的壳", "绿色", "圆壳"],
      ["frog", "frog animal", "青蛙", "qing wa", "绿色，会跳", "绿色", "长后腿"],
      ["penguin", "penguin animal", "企鹅", "qi e", "黑白色，摇摇走", "黑白", "短翅膀"],
      ["elephant", "elephant animal", "大象", "da xiang", "灰色，鼻子长", "灰色", "长鼻子"],
      ["giraffe", "giraffe animal", "长颈鹿", "chang jing lu", "脖子很长", "黄色", "长脖子"],
      ["panda", "panda animal", "熊猫", "xiong mao", "黑白色，爱吃竹子", "黑白", "圆耳朵"],
      ["lion", "lion animal", "狮子", "shi zi", "金黄色，鬃毛多", "金黄", "鬃毛"],
      ["zebra", "zebra animal", "斑马", "ban ma", "黑白条纹", "黑白", "条纹"],
      ["koala", "koala animal", "考拉", "kao la", "灰色，抱树枝", "灰色", "圆耳朵"],
      ["dolphin", "dolphin animal", "海豚", "hai tun", "蓝灰色，会跃出水面", "蓝灰", "流线形"],
    ],
  },
  {
    id: "plants",
    label: "植物",
    sceneSlug: "scene-plants",
    sceneQuery: "botanical garden flowers leaves seedlings",
    title: "植物",
    subtitle: "观察叶子、花朵和小小的芽。",
    theme: "leaf",
    question: "它的叶子是什么颜色？花朵是什么形状？",
    items: [
      ["sunflower", "sunflower flower", "向日葵", "xiang ri kui", "黄色，朝太阳", "黄色", "大花盘"],
      ["lotus", "lotus leaf flower", "荷叶", "he ye", "绿色，圆圆的", "绿色", "圆形"],
      ["seedling", "seedling plant", "小树苗", "xiao shu miao", "嫩绿，慢慢长高", "嫩绿", "小叶子"],
      ["fern", "fern plant", "蕨类", "jue lei", "绿色，像羽毛", "绿色", "卷叶"],
      ["rose", "rose flower", "玫瑰", "mei gui", "红色，有花瓣", "红色", "层层花瓣"],
      ["tulip", "tulip flower", "郁金香", "yu jin xiang", "杯子形的花", "粉色", "杯形"],
      ["daisy", "daisy flower", "雏菊", "chu ju", "白色花瓣，黄色花心", "白色", "小圆花"],
      ["bamboo", "bamboo plant", "竹子", "zhu zi", "绿色，一节一节", "绿色", "长杆"],
      ["pine", "pine tree", "松树", "song shu", "针一样的叶子", "深绿", "针叶"],
      ["maple", "maple leaf", "枫叶", "feng ye", "秋天会变红", "红色", "掌形叶"],
      ["cactus", "cactus plant", "仙人掌", "xian ren zhang", "绿色，有小刺", "绿色", "厚厚的茎"],
      ["grass", "green grass plant", "小草", "xiao cao", "细细长长", "绿色", "细长叶"],
      ["lavender", "lavender flower", "薰衣草", "xun yi cao", "紫色，有香味", "紫色", "小花穗"],
      ["orchid", "orchid flower", "兰花", "lan hua", "花瓣优雅", "紫白", "弯花瓣"],
      ["mushroom", "mushroom", "蘑菇", "mo gu", "像一把小伞", "棕色", "伞形"],
      ["water-lily", "water lily flower", "睡莲", "shui lian", "开在水面上", "粉色", "圆花瓣"],
      ["ivy", "ivy leaves plant", "常春藤", "chang chun teng", "会攀爬", "绿色", "藤蔓"],
      ["mint", "mint plant leaves", "薄荷", "bo he", "叶子清香", "绿色", "椭圆叶"],
      ["clover", "clover plant", "三叶草", "san ye cao", "三片小叶子", "绿色", "三片叶"],
      ["peony", "peony flower", "牡丹", "mu dan", "花朵大而饱满", "粉色", "大花朵"],
    ],
  },
  {
    id: "vegetables",
    label: "蔬菜",
    sceneSlug: "scene-vegetables",
    sceneQuery: "vegetable garden tomatoes carrots broccoli corn",
    title: "蔬菜",
    subtitle: "来自大地的礼物，营养又美味。",
    theme: "vegetable",
    question: "它是什么颜色？长得像什么形状？",
    items: [
      ["tomato", "tomato vegetable", "西红柿", "xi hong shi", "红色，酸甜可口", "红色", "圆形"],
      ["carrot", "carrot vegetable", "胡萝卜", "hu luo bo", "橙色，长条形", "橙色", "长条形"],
      ["broccoli", "broccoli vegetable", "西兰花", "xi lan hua", "绿色，像小树", "绿色", "树状"],
      ["corn", "corn vegetable", "玉米", "yu mi", "黄色，一粒一粒", "黄色", "长条形"],
      ["eggplant", "eggplant vegetable", "茄子", "qie zi", "紫色，弯弯的", "紫色", "长圆形"],
      ["pumpkin", "pumpkin vegetable", "南瓜", "nan gua", "橙色，圆圆的", "橙色", "圆形"],
      ["cucumber", "cucumber vegetable", "黄瓜", "huang gua", "绿色，脆脆的", "绿色", "长条形"],
      ["potato", "potato vegetable", "土豆", "tu dou", "棕黄色，圆滚滚", "棕黄", "椭圆形"],
      ["pepper", "bell pepper vegetable", "彩椒", "cai jiao", "颜色鲜艳，像小灯笼", "红黄", "灯笼形"],
      ["spinach", "spinach vegetable", "菠菜", "bo cai", "绿色，叶子软", "绿色", "叶片"],
      ["lettuce", "lettuce vegetable", "生菜", "sheng cai", "叶子一层层", "浅绿", "叶片"],
      ["cabbage", "cabbage vegetable", "卷心菜", "juan xin cai", "叶子卷成球", "浅绿", "圆球"],
      ["mushroom", "mushroom vegetable", "香菇", "xiang gu", "棕色，像小伞", "棕色", "伞形"],
      ["onion", "onion vegetable", "洋葱", "yang cong", "一层一层", "紫白", "圆形"],
      ["garlic", "garlic vegetable", "大蒜", "da suan", "白色，一瓣瓣", "白色", "瓣形"],
      ["pea", "green peas vegetable", "豌豆", "wan dou", "绿色，小圆粒", "绿色", "小圆粒"],
      ["radish", "radish vegetable", "白萝卜", "bai luo bo", "白色，长长的", "白色", "长条形"],
      ["celery", "celery vegetable", "芹菜", "qin cai", "绿色，有长茎", "绿色", "长茎"],
      ["cauliflower", "cauliflower vegetable", "花菜", "hua cai", "白色，像小花", "白色", "花状"],
      ["sweet-potato", "sweet potato vegetable", "红薯", "hong shu", "红皮，甜甜的", "红棕", "长圆形"],
    ],
  },
  {
    id: "fruits",
    label: "水果",
    sceneSlug: "scene-fruits",
    sceneQuery: "fruit basket orchard apple banana strawberry orange grapes",
    title: "水果",
    subtitle: "闻一闻果香，认识颜色和味道。",
    theme: "fruit",
    question: "它是什么颜色？尝起来可能是什么味道？",
    items: [
      ["apple", "red apple fruit", "苹果", "ping guo", "红色，圆圆的", "红色", "圆形"],
      ["banana", "banana fruit", "香蕉", "xiang jiao", "黄色，弯弯的", "黄色", "弯形"],
      ["strawberry", "strawberry fruit", "草莓", "cao mei", "红色，有小点", "红色", "心形"],
      ["orange", "orange fruit", "橙子", "cheng zi", "橙色，多汁", "橙色", "圆形"],
      ["grape", "purple grapes fruit", "葡萄", "pu tao", "紫色，一串串", "紫色", "小圆粒"],
      ["pear", "pear fruit", "梨", "li", "黄绿色，甜甜的", "黄绿", "葫芦形"],
      ["peach", "peach fruit", "桃子", "tao zi", "粉色，有绒毛", "粉色", "圆形"],
      ["watermelon", "watermelon fruit", "西瓜", "xi gua", "绿色外皮，红色果肉", "绿红", "大圆形"],
      ["pineapple", "pineapple fruit", "菠萝", "bo luo", "黄色，有格纹", "黄色", "椭圆形"],
      ["mango", "mango fruit", "芒果", "mang guo", "黄色，香香的", "黄色", "椭圆形"],
      ["kiwi", "kiwi fruit", "猕猴桃", "mi hou tao", "棕色外皮，绿色果肉", "棕绿", "椭圆形"],
      ["lemon", "lemon fruit", "柠檬", "ning meng", "黄色，酸酸的", "黄色", "椭圆形"],
      ["blueberry", "blueberry fruit", "蓝莓", "lan mei", "蓝紫色，小小的", "蓝紫", "小圆粒"],
      ["cherry", "cherry fruit", "樱桃", "ying tao", "红色，小圆果", "红色", "小圆形"],
      ["plum", "plum fruit", "李子", "li zi", "紫红色，圆圆的", "紫红", "圆形"],
      ["pomegranate", "pomegranate fruit", "石榴", "shi liu", "红色，籽很多", "红色", "圆形"],
      ["dragon-fruit", "dragon fruit", "火龙果", "huo long guo", "红皮，黑籽", "红白", "椭圆形"],
      ["coconut", "coconut fruit", "椰子", "ye zi", "棕色，壳硬硬", "棕色", "圆形"],
      ["lychee", "lychee fruit", "荔枝", "li zhi", "红色外壳，白色果肉", "红白", "小圆形"],
      ["papaya", "papaya fruit", "木瓜", "mu gua", "橙色果肉，长圆形", "橙色", "长圆形"],
    ],
  },
  {
    id: "vehicles",
    label: "交通工具",
    sceneSlug: "scene-vehicles",
    sceneQuery: "children picture book city road vehicles train airplane boat",
    title: "交通工具",
    subtitle: "看看它们在哪里行驶，听听出发的声音。",
    theme: "sky",
    question: "它是在路上、水里，还是天上移动？",
    items: [
      ["car", "car vehicle", "小汽车", "xiao qi che", "红色，跑在马路上", "红色", "小车形"],
      ["bus", "bus vehicle", "公交车", "gong jiao che", "黄色，能坐很多人", "黄色", "长方形"],
      ["fire-truck", "fire truck vehicle", "消防车", "xiao fang che", "红色，帮助灭火", "红色", "长车身"],
      ["ambulance", "ambulance vehicle", "救护车", "jiu hu che", "白色，救助病人", "白色", "方车厢"],
      ["police-car", "police car vehicle", "警车", "jing che", "蓝白色，保护大家", "蓝白", "小车形"],
      ["bicycle", "bicycle vehicle", "自行车", "zi xing che", "两个轮子，脚踩前进", "蓝色", "双轮形"],
      ["motorcycle", "motorcycle vehicle", "摩托车", "mo tuo che", "速度快，轮子圆", "黑色", "双轮形"],
      ["train", "train vehicle", "火车", "huo che", "一节一节，沿轨道走", "绿色", "长条形"],
      ["high-speed-rail", "high speed rail vehicle", "高铁", "gao tie", "白色，跑得很快", "白色", "流线形"],
      ["subway", "subway train vehicle", "地铁", "di tie", "在城市地下穿行", "银色", "长车厢"],
      ["airplane", "airplane vehicle", "飞机", "fei ji", "白色，飞上天空", "白色", "大翅膀"],
      ["helicopter", "helicopter vehicle", "直升机", "zhi sheng ji", "有旋转的螺旋桨", "橙色", "螺旋桨"],
      ["ship", "ship vehicle", "轮船", "lun chuan", "蓝白色，航行在水面", "蓝白", "船形"],
      ["sailboat", "sailboat vehicle", "帆船", "fan chuan", "白帆鼓鼓，随风走", "白色", "三角帆"],
      ["truck", "truck vehicle", "货车", "huo che", "车厢大，能运东西", "橙色", "大车厢"],
      ["excavator", "excavator vehicle", "挖掘机", "wa jue ji", "黄色，有长长的机械臂", "黄色", "长机械臂"],
      ["tractor", "tractor vehicle", "拖拉机", "tuo la ji", "在田地里慢慢开", "绿色", "大轮子"],
      ["school-bus", "school bus vehicle", "校车", "xiao che", "黄色，送小朋友上学", "黄色", "长方形"],
      ["taxi", "taxi vehicle", "出租车", "chu zu che", "黄色，载乘客去目的地", "黄色", "小车形"],
      ["hot-air-balloon", "hot air balloon vehicle", "热气球", "re qi qiu", "彩色，慢慢飘上天", "彩色", "圆气球"],
    ],
  },
  {
    id: "daily-items",
    label: "日常用品",
    sceneSlug: "scene-daily-items",
    sceneQuery: "children picture book cozy home daily objects toys school supplies",
    title: "日常用品",
    subtitle: "找一找家里的小物件，说说它们怎么用。",
    theme: "home",
    question: "它放在哪里？我们平时会怎样使用它？",
    items: [
      ["cup", "cup daily item", "杯子", "bei zi", "用来喝水，拿在手里", "蓝色", "圆柱形"],
      ["bowl", "bowl daily item", "碗", "wan", "吃饭时装米饭和汤", "白色", "圆形"],
      ["spoon", "spoon daily item", "勺子", "shao zi", "舀一舀，慢慢吃", "银色", "长柄形"],
      ["toothbrush", "toothbrush daily item", "牙刷", "ya shua", "早晚刷牙，牙齿亮亮", "绿色", "长条形"],
      ["towel", "towel daily item", "毛巾", "mao jin", "软软的，可以擦手擦脸", "粉色", "长方形"],
      ["backpack", "backpack daily item", "书包", "shu bao", "背在肩上，装书本", "黄色", "包形"],
      ["shoes", "shoes daily item", "鞋子", "xie zi", "穿在脚上，保护小脚", "红色", "成双形"],
      ["hat", "hat daily item", "帽子", "mao zi", "戴在头上，遮太阳", "蓝色", "半圆形"],
      ["umbrella", "umbrella daily item", "雨伞", "yu san", "下雨时撑起来", "彩色", "伞形"],
      ["clock", "clock daily item", "闹钟", "nao zhong", "滴答滴答，提醒时间", "橙色", "圆形"],
      ["lamp", "lamp daily item", "台灯", "tai deng", "晚上发亮，照着书本", "黄色", "灯罩形"],
      ["chair", "chair daily item", "椅子", "yi zi", "坐下来，休息一下", "棕色", "方形"],
      ["table", "table daily item", "桌子", "zhuo zi", "可以放书和玩具", "棕色", "长方形"],
      ["bed", "bed daily item", "小床", "xiao chuang", "睡觉时躺在上面", "浅蓝", "长方形"],
      ["pillow", "pillow daily item", "枕头", "zhen tou", "软软的，垫着小脑袋", "白色", "圆角形"],
      ["blocks", "blocks daily item", "积木", "ji mu", "一块一块，搭高高", "彩色", "方块形"],
      ["ball", "ball daily item", "皮球", "pi qiu", "圆滚滚，会弹起来", "红蓝", "圆形"],
      ["crayon", "crayon daily item", "蜡笔", "la bi", "画出彩色线条", "彩色", "短条形"],
      ["book", "book daily item", "图画书", "tu hua shu", "一页一页，讲故事", "绿色", "方形"],
      ["notebook", "notebook daily item", "本子", "ben zi", "可以写字和画画", "白色", "长方形"],
    ],
  },
  {
    id: "weather-nature",
    label: "天气与自然",
    sceneSlug: "scene-weather-nature",
    sceneQuery: "realistic educational nature weather landscape sun moon stars clouds rain snow rainbow river sea mountain",
    title: "天气与自然",
    subtitle: "抬头看看天空，低头摸摸大地。",
    theme: "weather",
    question: "它出现在天空、陆地，还是水边？你见过它吗？",
    items: [
      ["sun", "sun nature weather", "太阳", "tai yang", "金黄色，带来温暖光亮", "金黄", "圆形"],
      ["moon", "moon nature night", "月亮", "yue liang", "夜晚出现，弯弯亮亮", "银白", "弯形"],
      ["stars", "stars night sky", "星星", "xing xing", "夜空里一闪一闪", "银白", "小星形"],
      ["cloud", "cloud weather", "云朵", "yun duo", "白白软软，飘在天上", "白色", "团状"],
      ["rain", "rain weather", "雨", "yu", "一滴一滴落下来", "透明", "水滴形"],
      ["snow", "snow weather", "雪", "xue", "白白的，轻轻飘落", "白色", "雪花形"],
      ["wind", "wind weather", "风", "feng", "看不见，会吹动树叶", "无色", "流线形"],
      ["rainbow", "rainbow weather", "彩虹", "cai hong", "雨后出现，颜色很多", "彩色", "弧形"],
      ["lightning", "lightning weather", "闪电", "shan dian", "亮亮的，像折线", "亮黄", "折线形"],
      ["fog", "fog weather", "雾", "wu", "白茫茫，让远处变模糊", "灰白", "薄雾状"],
      ["mountain", "mountain nature", "山", "shan", "高高的，连着大地", "灰绿", "三角形"],
      ["river", "river nature", "小河", "xiao he", "水慢慢流向远方", "蓝色", "弯曲形"],
      ["sea", "sea ocean nature", "大海", "da hai", "蓝蓝的，浪花一层层", "蓝色", "广阔形"],
      ["beach", "beach nature", "沙滩", "sha tan", "软软的，有细沙", "金黄", "平面形"],
      ["stone", "stone nature", "石头", "shi tou", "硬硬的，形状不一样", "灰色", "不规则"],
      ["soil", "soil nature", "泥土", "ni tu", "棕色，植物从这里生长", "棕色", "颗粒状"],
      ["leaf", "leaf nature", "树叶", "shu ye", "绿色，长在树枝上", "绿色", "叶片形"],
      ["flower-bed", "flower bed nature", "花丛", "hua cong", "许多小花开在一起", "彩色", "簇状"],
      ["pond", "pond nature", "池塘", "chi tang", "水面安静，像小镜子", "蓝绿", "圆池形"],
      ["grassland", "grassland nature", "草地", "cao di", "绿绿的，可以奔跑玩耍", "绿色", "平面形"],
    ],
  },
  {
    id: "body-parts",
    label: "身体与五官",
    sceneSlug: "scene-body-parts",
    sceneQuery: "realistic educational body parts face hands feet anatomy for toddlers",
    title: "身体与五官",
    subtitle: "认识自己的身体，指一指，说一说。",
    theme: "body",
    question: "它在身体的哪里？我们会用它做什么？",
    items: [
      ["eyes", "eyes body part", "眼睛", "yan jing", "用来看东西，亮亮的", "黑白", "圆形"],
      ["ears", "ears body part", "耳朵", "er duo", "用来听声音，在头两边", "肤色", "弯形"],
      ["nose", "nose body part", "鼻子", "bi zi", "用来闻气味，在脸中间", "肤色", "凸起形"],
      ["mouth", "mouth body part", "嘴巴", "zui ba", "用来说话，也能吃东西", "红色", "弧形"],
      ["teeth", "teeth body part", "牙齿", "ya chi", "白白的，帮助咀嚼", "白色", "小块形"],
      ["tongue", "tongue body part", "舌头", "she tou", "尝味道，也帮助说话", "粉红", "柔软形"],
      ["hair", "hair body part", "头发", "tou fa", "长在头上，可以梳一梳", "黑色", "丝状"],
      ["face", "face body part", "脸", "lian", "有眼睛、鼻子和嘴巴", "肤色", "圆形"],
      ["hand", "hand body part", "手", "shou", "可以拿东西、挥一挥", "肤色", "掌形"],
      ["fingers", "fingers body part", "手指", "shou zhi", "一根一根，很灵活", "肤色", "细长形"],
      ["foot", "foot body part", "脚", "jiao", "踩在地上，帮助走路", "肤色", "脚掌形"],
      ["toes", "toes body part", "脚趾", "jiao zhi", "长在脚前面，小小的", "肤色", "小圆形"],
      ["arm", "arm body part", "胳膊", "ge bo", "可以伸直，也可以弯曲", "肤色", "长条形"],
      ["leg", "leg body part", "腿", "tui", "帮助站立、跑跑跳跳", "肤色", "长条形"],
      ["belly", "belly body part", "肚子", "du zi", "在身体中间，软软的", "肤色", "圆弧形"],
      ["back", "back body part", "背", "bei", "在身体后面，可以挺直", "肤色", "宽面形"],
      ["shoulder", "shoulder body part", "肩膀", "jian bang", "连接胳膊和身体", "肤色", "圆弧形"],
      ["knee", "knee body part", "膝盖", "xi gai", "腿弯曲的地方", "肤色", "圆形"],
      ["eyebrows", "eyebrows body part", "眉毛", "mei mao", "在眼睛上方，细细弯弯", "黑色", "弯线形"],
      ["neck", "neck body part", "脖子", "bo zi", "连接头和身体", "肤色", "圆柱形"],
    ],
  },
  {
    id: "jobs-tools",
    label: "职业与工具",
    sceneSlug: "scene-jobs-tools",
    sceneQuery: "realistic educational occupations tools doctor nurse teacher chef firefighter police driver farmer painter builder",
    title: "职业与工具",
    subtitle: "认识帮助大家工作的人和工具。",
    theme: "job",
    question: "这个职业会做什么？它常用什么工具？",
    items: [
      ["doctor", "doctor occupation", "医生", "yi sheng", "照顾病人，帮助身体恢复", "白色", "白大褂"],
      ["nurse", "nurse occupation", "护士", "hu shi", "细心照护，帮助量体温", "浅蓝", "制服"],
      ["teacher", "teacher occupation", "老师", "lao shi", "教大家学习新知识", "蓝色", "站立形"],
      ["chef", "chef occupation", "厨师", "chu shi", "做出香香的饭菜", "白色", "厨师帽"],
      ["firefighter", "firefighter occupation", "消防员", "xiao fang yuan", "勇敢灭火，保护大家", "红黄", "安全服"],
      ["police-officer", "police officer occupation", "警察", "jing cha", "维护秩序，帮助行人", "深蓝", "制服"],
      ["driver", "driver occupation", "司机", "si ji", "开车，把人送到目的地", "蓝色", "坐姿"],
      ["farmer", "farmer occupation", "农民", "nong min", "种庄稼，照顾田地", "绿色", "草帽"],
      ["painter", "painter occupation", "画家", "hua jia", "用颜色画出美丽图画", "彩色", "画笔"],
      ["builder", "builder occupation", "建筑工人", "jian zhu gong ren", "建房子，戴安全帽", "黄色", "安全帽"],
      ["stethoscope", "stethoscope tool", "听诊器", "ting zhen qi", "医生用它听心跳", "银黑", "弯管形"],
      ["blackboard", "blackboard tool", "黑板", "hei ban", "老师在上面写字画图", "深绿", "长方形"],
      ["spatula", "spatula tool", "锅铲", "guo chan", "厨师用它翻炒食物", "银色", "长柄形"],
      ["fire-hose", "fire hose tool", "水管", "shui guan", "消防员用它喷水灭火", "红色", "卷管形"],
      ["paintbrush", "paintbrush tool", "画笔", "hua bi", "蘸上颜色，画出线条", "棕色", "细长形"],
      ["hard-hat", "hard hat tool", "安全帽", "an quan mao", "保护头部，很结实", "黄色", "帽形"],
      ["wrench", "wrench tool", "扳手", "ban shou", "拧一拧，修理工具", "银色", "长条形"],
      ["syringe", "syringe tool", "注射器", "zhu she qi", "医院里常见的工具", "透明", "细长形"],
      ["notebook-tool", "notebook occupation tool", "记事本", "ji shi ben", "记录工作要点", "白色", "本子形"],
      ["seedling-tool", "seedling farming tool", "小铲子", "xiao chan zi", "种花种菜时会用到", "绿色", "铲形"],
    ],
  },
].map((category) => ({
  ...category,
  image: `/media/optimized/${category.sceneSlug}.webp?v=${imageVersion}`,
  items: category.items.map(([slug, query, name, pinyin, cue, color, shape]) => ({
    slug: `${category.id}-${slug}`,
    query,
    name,
    pinyin,
    cue,
    color,
    shape,
    image: `/media/optimized/${category.id}-${slug}.webp?v=${imageVersion}`,
    focusPosition: "center",
    focusScale: 1,
  })),
}));
